inventory_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('manager.urls', 'manager'), namespace='manager'))
]

manager/urls.py
from django.urls import path

from manager.views import BookingList, Booking, cancel_booking, BookingEditView

urlpatterns = [
    path('', BookingList.as_view(), name="list"),
    path('book/', Booking.as_view(), name="book"),
    path('update/<int:pk>', BookingEditView.as_view(), name="update"),
    path('cancel/<int:id>', cancel_booking, name="cancel"),
]

manager/models.py
from django.db import models


class Inventory(models.Model):
    """
    This model will maintain the inventory related data

    `title`
        Inventory title or short description

    `description`
        Inventory description

    `remaining_count`
        Maintaining count to hide/show book and cancel features on ui

    `expiration_date`
        Inventory expiry time
    """
    title = models.CharField(null=False, blank=False, max_length=255)
    description = models.TextField()
    remaining_count = models.IntegerField(default=0)
    expiration_date = models.DateField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Inventory"


class Member(models.Model):
    """
    This model is used to store members related data

    `name`
        First name of the member

    `surname`
        Last name of the member

    `booking_count`
        Maintaining count related to each member

    `date_joined`
        Date of joining as member
    """
    name = models.CharField(null=False, blank=False, max_length=120)
    surname = models.CharField(max_length=120)
    booking_count = models.IntegerField(default=0)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} {}".format(self.name, self.surname)

manager/forms.py
from django import forms

from manager.models import Inventory, Member


class MemberForm(forms.ModelForm):
    inventory = forms.ModelChoiceField(queryset=Inventory.objects.all())

    class Meta:
        model = Member
        exclude = ['booking_count', 'date_joined']

    def clean(self):
        cleaned_data = super(MemberForm, self).clean()
        existing_instance = Member.objects.filter(
            name=cleaned_data['name'], surname=cleaned_data['surname']).first()
        if existing_instance and existing_instance.booking_count >= 2:
            self.add_error('name', 'Booking limit reach to its maximum of 2.')
        return cleaned_data

    def save(self, commit=True):
        existing_instance = Member.objects.filter(
            name=self.instance.name, surname=self.instance.surname).first()
        if existing_instance:
            self.instance = existing_instance
        self.instance.booking_count += 1
        return super().save(commit=commit)

manager/views.py
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy

from django.views.generic import CreateView, ListView, UpdateView

from manager.forms import MemberForm
from manager.models import Member


class BookingList(ListView):
    """
    BookingList view class to list all active members and inventory count
    """
    model = Member
    template_name = 'member_list.html'

    def get_queryset(self):
        queryset = super(BookingList, self).get_queryset()
        return queryset.order_by('-date_joined')


class Booking(CreateView):
    """
    Booking view class to add new member against the available inventory
    """
    model = Member
    form_class = MemberForm
    template_name = 'booking.html'
    success_url = reverse_lazy('manager:list')


class BookingEditView(UpdateView):
    """
    BookingEdit view class to update existing member against the available inventory
    """
    model = Member
    form_class = MemberForm
    template_name = 'booking.html'
    success_url = reverse_lazy('manager:list')


def cancel_booking(request, id):
    """
    Cancel view method to remove existing member against the available inventory
    """
    obj = Member.objects.get(id=id)
    obj.booking_count -= 1
    obj.save()
    return redirect(reverse('manager:list'))

manager/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Inventory Management</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Inventory Management</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'manager:list' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'manager:book' %}">Create New Member</a>
            </li>

          </ul>
        </div>
      </div>
    </nav>
    {% block base_container %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

manager/templates/booking.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block base_container %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-6">
                <form action="{% url 'manager:book' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

manager/templates/member_list.html
{% extends 'base.html' %}


{% block base_container %}
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Name</th>
                      <th scope="col">Surname</th>
                      <th scope="col">Booking Count</th>
                      <th scope="col">Joining Date</th>
                      <th scope="col">Book</th>
                      <th scope="col">Cancel</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for obj in object_list %}
                    <tr>
                      <td>{{obj.name}}</td>
                      <td>{{obj.surname}}</td>
                      <td>{{obj.booking_count}}</td>
                      <td>{{obj.date_joined}}</td>
                      <td>
                          {% if obj.booking_count < 2 %}
                            <a href="{% url 'manager:update' obj.id %}">Book</a>
                          {% endif %}
                      </td>
                      <td>
                          {% if obj.booking_count > 0 %}
                            <a href="{% url 'manager:cancel' obj.id %}">Cancel</a>
                          {% endif %}
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}